# -*- coding: utf-8 -*-
# @author    hulig


# 10号线配置 zabbix
TEN_CONFIGURATION_DATA_POSITIVE = {
    'zbx5': 'mdyy_m',
    'zbx6': 'mdyy_s',
    'zbx7': 'mdsj_m',
    'zbx8': 'mdsj_s',
    'Zabbix server': 'mdjl_m',
    'zbx2': 'mdjl_s',
    'zbx3': 'mdjl_m_1',
    'zbx4': 'mdjl_s_1',
    'zbx9': 'mdtxqzj_m',
    'zbx10': 'mdtxqzj_s',
    'zbx11': 'xhycz',
    'zbx12': 'zbycz',
    'zbx13': 'ccdd',
    'zbx14': 'jxdd',
    'zbx15': 'ccjx',
    'zbx16': 'gdl_qzj_m',
    'zbx17': 'gdl_qzj_s',
    'zbx18': 'gdl_xhycz',
    'zbx19': 'gdl_zbycz',
    'zbx20': 'gdl_ccdd',
    'zbx21': 'gdl_ccjx',
    'zbx22': 'gdl_jxdd',
    'zbx23': 'gdl_pbgzz',
    'zbx24': 'gdl_ctqzd',
    'zbx25': 'whgz_m',
    'zbx26': 'ctqzd',
    'zbx27': 'pbgzz',
    'zbx30': 'tpy_ctqzd',
    'zbx31': 'tpy_pbgzz',
}

# 10号线配置 zabbix
TEN_CONFIGURATION_DATA_REVERSE = {
    'mdyy_m': 'zbx5',
    'mdyy_s': 'zbx6',
    'mdsj_m': 'zbx7',
    'mdsj_s': 'zbx8',
    'mdjl_m': 'Zabbix server',
    'mdjl_s': 'zbx2',
    'mdjl_m_1': 'zbx3',
    'mdjl_s_1': 'zbx4',
    'mdtxqzj_m': 'zbx9',
    'mdtxqzj_s': 'zbx10',
    'xhycz': 'zbx11',
    'zbycz': 'zbx12',
    'ccdd': 'zbx13',
    'jxdd': 'zbx14',
    'ccjx': 'zbx15',
    'gdl_qzj_m': 'zbx16',
    'gdl_qzj_s': 'zbx17',
    'gdl_xhycz': 'zbx18',
    'gdl_zbycz': 'zbx19',
    'gdl_ccdd': 'zbx20',
    'gdl_ccjx': 'zbx21',
    'gdl_jxdd': 'zbx22',
    'gdl_pbgzz': 'zbx23',
    'gdl_ctqzd': 'zbx24',
    'whgz_m': 'zbx25',
    'ctqzd': 'zbx26',
    'pbgzz': 'zbx27',
    'tpy_ctqzd': 'zbx30',
    'tpy_pbgzz': 'zbx31',
}

# 获取对应的名字
TEN_CONFIGURATION_NAME = {
    'zbx5': '板桥应用服务器主机',
    'zbx6': '板桥应用服务器备机',
    'zbx7': '板桥数据库服务器主机',
    'zbx8': '板桥数据库服务器备机',
    'Zabbix server': '板桥进路管理服务器主机',
    'zbx2': '板桥进路管理服务器备机',
    'zbx3': '板桥进路数据库服务器主机',
    'zbx4': '板桥进路数据库服务器备机',
    'zbx9': '板桥通信前置机主机',
    'zbx10': '板桥通信前置机备机',
    'zbx11': '板桥信号员操作工作站',
    'zbx12': '板桥值班员操作工作站',
    'zbx13': '板桥车场调度工作站',
    'zbx14': '板桥检修调度工作站',
    'zbx15': '板桥车辆检修工作站',
    'zbx16': '高大路通信前置机主机',
    'zbx17': '高大路通信前置机备机',
    'zbx18': '高大路信号员操作工作站',
    'zbx19': '高大路值班员操作工作站',
    'zbx20': '高大路车场调度工作站',
    'zbx21': '高大路车场检修工作站',
    'zbx22': '高大路检修调度工作站',
    'zbx23': '高大路派班工作站',
    'zbx24': '高大路出退勤终端',
    'zbx25': '板桥维护工作站',
    'zbx26': '板桥出退勤终端',
    'zbx27': '板桥派班工作站',
    'zbx30': '太平园出退勤终端',
    'zbx31': '太平园派班工作站',
}

TEN_ZABBIX_IP = {
    'zbx5': '172.21.0.5',
    'zbx6': '172.21.0.6',
    'zbx7': '172.21.0.7',
    'zbx8': '172.21.0.8',
    'Zabbix server': '172.21.0.1',
    'zbx2': '172.21.0.2',
    'zbx3': '172.21.0.3',
    'zbx4': '172.21.0.4',
    'zbx9': '172.21.0.9',
    'zbx10': '172.21.0.10',
    'zbx11': '172.21.0.13',
    'zbx12': '172.21.0.12',
    'zbx13': '172.21.0.11',
    'zbx14': '172.21.0.15',
    'zbx15': '172.21.0.11',
    'zbx16': '172.25.0.1',
    'zbx17': '172.25.0.2',
    'zbx18': '172.25.0.5',
    'zbx19': '172.25.0.4',
    'zbx20': '172.25.0.3',
    'zbx21': '172.25.0.6',
    'zbx22': '172.25.0.3',
    'zbx23': '172.25.0.12',
    'zbx24': '172.25.0.11',
    'zbx25': '172.21.0.16',
    'zbx26': '172.21.0.18',
    'zbx27': '172.21.0.19',
    'zbx30': '172.25.0.13',
    'zbx31': '172.25.0.14',
    'switch3': '172.21.0.253',
    'switch4': '172.22.0.253',
    'switch1': '172.25.0.100',
    'switch2': '172.26.0.100',
}

TEN_DATAS = [
    {'zabbix': 'zbx5', 'server_name': '板桥应用服务器五', 'image_change': 'mdyy_m', 'ip': '172.21.0.5',
     'name': 'bq_yyfwq'},
    {'zabbix': 'zbx6', 'server_name': '板桥应用服务器六', 'image_change': 'mdyy_s', 'ip': '172.21.0.6',
     'name': 'bq_yyfwq'},
    {'zabbix': 'zbx7', 'server_name': '板桥数据库服务器一', 'image_change': 'mdsj_m', 'ip': '172.21.0.7',
     'name': 'bq_sjkfwq'},
    {'zabbix': 'zbx8', 'server_name': '板桥数据库服务器二', 'image_change': 'mdsj_s', 'ip': '172.21.0.8',
     'name': 'bq_sjkfwq'},
    {'zabbix': 'Zabbix server', 'server_name': '板桥应用服务器一', 'image_change': 'mdjl_m', 'ip': '172.21.0.1',
     'name': 'bq_jlglfwq'},
    {'zabbix': 'zbx2', 'server_name': '板桥应用服务器二', 'image_change': 'mdjl_s', 'ip': '172.21.0.2',
     'name': 'bq_jlglfwq'},
    {'zabbix': 'zbx3', 'server_name': '板桥应用服务器三', 'image_change': 'mdjl_m_1', 'ip': '172.21.0.3',
     'name': 'bq_jlsjkfwq'},
    {'zabbix': 'zbx4', 'server_name': '板桥应用服务器四', 'image_change': 'mdjl_s_1', 'ip': '172.21.0.4',
     'name': 'bq_jlsjkfwq'},
    {'zabbix': 'zbx9', 'server_name': '板桥通信前置机主机', 'image_change': 'mdtxqzj_m', 'ip': '172.21.0.9',
     'name': 'bq_txqzj'},
    {'zabbix': 'zbx10', 'server_name': '板桥通信前置机备机', 'image_change': 'mdtxqzj_s', 'ip': '172.21.0.10',
     'name': 'bq_txqzj'},
    {'zabbix': 'zbx11', 'server_name': '板桥信号员操作工作站', 'image_change': 'xhycz', 'ip': '172.21.0.13',
     'name': 'bq_xhyczgzz'},
    {'zabbix': 'zbx12', 'server_name': '板桥值班员操作工作站', 'image_change': 'zbycz', 'ip': '172.21.0.12',
     'name': 'bq_zbyczgzz'},
    {'zabbix': 'zbx13', 'server_name': '板桥车场调度工作站', 'image_change': 'ccdd', 'ip': '172.21.0.11',
     'name': 'bq_ccddgzz'},
    {'zabbix': 'zbx14', 'server_name': '板桥检修调度工作站', 'image_change': 'jxdd', 'ip': '172.21.0.15',
     'name': 'bq_jxddgzz'},
    {'zabbix': 'zbx15', 'server_name': '板桥车辆检修工作站', 'image_change': 'ccjx', 'ip': '172.21.0.11',
     'name': 'bq_cljxgzz'},
    {'zabbix': 'zbx16', 'server_name': '高大路通信前置机主机', 'image_change': 'gdl_qzj_m', 'ip': '172.25.0.1',
     'name': 'gdl_txqzj'},
    {'zabbix': 'zbx17', 'server_name': '高大路通信前置机备机', 'image_change': 'gdl_qzj_s', 'ip': '172.25.0.2',
     'name': 'gdl_txqzj'},
    {'zabbix': 'zbx18', 'server_name': '高大路信号员操作工作站', 'image_change': 'gdl_xhycz', 'ip': '172.25.0.5',
     'name': 'gdl_xhyczgzz'},
    {'zabbix': 'zbx19', 'server_name': '高大路值班员操作工作站', 'image_change': 'gdl_zbycz', 'ip': '172.25.0.4',
     'name': 'gdl_zbyccgzz'},
    {'zabbix': 'zbx20', 'server_name': '高大路车场调度工作站', 'image_change': 'gdl_ccdd', 'ip': '172.25.0.3',
     'name': 'gdl_ccddgzz'},
    {'zabbix': 'zbx21', 'server_name': '高大路车场检修工作站', 'image_change': 'gdl_ccjx', 'ip': '172.25.0.6',
     'name': 'gdl_cljxgzz'},
    {'zabbix': 'zbx22', 'server_name': '高大路检修调度工作站', 'image_change': 'gdl_jxdd', 'ip': '172.25.0.3',
     'name': 'gdl_jxddgzz'},
    {'zabbix': 'zbx23', 'server_name': '高大路派班工作站', 'image_change': 'gdl_pbgzz', 'ip': '172.25.0.12',
     'name': 'gdl_pbgzz'},
    {'zabbix': 'zbx24', 'server_name': '高大路出退勤终端', 'image_change': 'gdl_ctqzd', 'ip': '172.25.0.11',
     'name': 'gdl_tcqgzd'},
    {'zabbix': 'zbx25', 'server_name': '板桥维护工作站', 'image_change': 'whgz_m', 'ip': '172.21.0.16',
     'name': 'bq_whgzz'},
    {'zabbix': 'zbx26', 'server_name': '板桥出退勤终端', 'image_change': 'ctqzd', 'ip': '172.21.0.18',
     'name': 'bq_tcqzd'},
    {'zabbix': 'zbx27', 'server_name': '板桥派班工作站', 'image_change': 'pbgzz', 'ip': '172.21.0.19',
     'name': 'bq_pbgzz'},
    {'zabbix': 'zbx30', 'server_name': '太平园出退勤终端', 'image_change': 'tpy_ctqzd', 'ip': '172.25.0.13',
     'name': 'tpy_tcqzd'},
    {'zabbix': 'zbx31', 'server_name': '太平园派班工作站', 'image_change': 'tpy_pbgzz', 'ip': '172.25.0.14',
     'name': 'tpy_pbgzz'},
]

Ten_ZABBIX_KEY = {
    'zbx5': '板桥应用服务器五',
    'zbx6': '板桥应用服务器六',
    'zbx7': '板桥数据库服务器一',
    'zbx8': '板桥数据库服务器二',
    'Zabbix server': '板桥应用服务器一',
    'zbx2': '板桥应用服务器二',
    'zbx3': '板桥应用服务器三',
    'zbx4': '板桥应用服务器四',
    'zbx9': '板桥通信前置机主机',
    'zbx10': '板桥通信前置机备机',
    'zbx11': '板桥信号员操作工作站',
    'zbx12': '板桥值班员操作工作站',
    'zbx13': '板桥车场调度工作站',
    'zbx14': '板桥检修调度工作站',
    'zbx15': '板桥车辆检修工作站',
    'zbx16': '高大路通信前置机主机',
    'zbx17': '高大路通信前置机备机',
    'zbx18': '高大路信号员操作工作站',
    'zbx19': '高大路值班员操作工作站',
    'zbx20': '高大路车场调度工作站',
    'zbx21': '高大路车场检修工作站',
    'zbx22': '高大路检修调度工作站',
    'zbx23': '高大路派班工作站',
    'zbx24': '高大路出退勤终端',
    'zbx25': '板桥维护工作站',
    'zbx26': '板桥出退勤终端',
    'zbx27': '板桥派班工作站',
    'zbx30': '太平园出退勤终端',
    'zbx31': '太平园派班工作站',
    'switch3': '板桥接入交换机主机',
    'switch4': '板桥接入交换机备机',
    'switch1': '板桥核心交换机主机',
    'switch2': '板桥核心交换机备机',
}

