# -*- coding: utf-8 -*-
{
    'name': "metro_park_maintenance",
    'summary': """设备维护""",
    'description': """
        富能通车辆维护
    """,

    'author': "crax",
    'website': "http://www.funenc.com",

    'category': 'funenc',
    'version': '1.0',

    'depends': ['base', 'metro_park_base'],

    'data': [
        'security/ir.model.access.csv',
        "views/assets.xml",
        "views/train_dev.xml",
        "views/dev_batch.xml",
        "views/train_miles.xml",
        "views/operation_record.xml",
        "views/dev_import_wizard.xml",
        "views/repair_rule.xml",
        "views/train_dev_day_mile_set.xml",
        "views/history_miles.xml",
        "views/train_miles_set_wizard.xml",
        "views/year_plan.xml",
        "views/year_plan_summary.xml",
        "views/plan_data.xml",
        "views/repair_param.xml",
        "views/year_mile_wizard.xml",
        "views/month_plan.xml",
        "views/year.xml",
        "views/month.xml",
        "views/year_plan_wizard.xml",
        "views/plan_config_data.xml",
        "views/year_plan_compute_wizard.xml",
        "views/month_plan_wizard.xml",
        "views/week_plan.xml",
        "views/week_plan_wizard.xml",
        "views/repair_tmp_rule.xml",
        "views/day.xml",
        "views/day_plan.xml",
        "views/holidays.xml",
        "views/day_plan_wizard.xml",
        "views/maintaince_config.xml",
        "views/plan_data_rule_info.xml",
        "data/miles_set_sequence.xml",
        "data/repair_param.xml",
        "data/year.xml",
        "data/month.xml",
        "data/week.xml",
        "data/sequence_number.xml",
        "data/repair_rule_sequence.xml",
        "data/day.xml",
        'data/group_data.xml',
        'data/year_dates.xml',
        'data/ir_cron.xml',
        'data/bdms.xml',
        'views/menus.xml',
        "views/add_day_plan_data_wizard.xml",
        'views/day_plan_wizard.xml',
        'views/year_plan_import_wizard.xml',
        'views/maintaince_order.xml',
        'views/order_assign_wizard.xml',
        'views/train_miles_export_wizard.xml',
        'views/maintaince_order_wizard.xml',
        'views/timing_task.xml',
        'views/month_plan_import_wizard.xml',
        'views/rule_count_constrain.xml',
        'views/month_plan_import_wizard.xml',
        'views/month_plan_compute_wizard.xml',
        'views/offset_info.xml',
        'views/plan_log.xml',
        'views/pms_timing_task.xml',
        'views/pms_department.xml',
        'views/last_repair_info.xml',
        'views/year_plan_clear_wizard.xml',
        'views/year_plan_history_info.xml',
        'views/import_month_works.xml',
        'views/month_plan_clear_wizard.xml',
        'views/import_week_plan.xml',
        'views/white_list.xml',
        'views/export_produce_plan_wizard.xml',
        'views/balance_rule_offset.xml',
        'views/balance_offset_wizard.xml',
        'views/update_balance_offset.xml',
        'views/import_offset_wizard.xml',
        'views/month_repair_count.xml',
        'views/month_plan_delta_info.xml',
        'views/max_repair_info.xml',
        'views/import_produce_work_class.xml',
        'views/mile_repair_history.xml',
        'views/temp_rule_plan_history.xml',
        'views/day_plan_limit.xml',
        'views/user_config.xml',
        'views/tcms_vehicle_data.xml',

        'views/bdms/malfunction_repair.xml',
        'views/bdms/alarm_device.xml',
        'wizard/vehicle_history_import.xml',
        'wizard/vehicle_history_add.xml',
        'wizard/vehicle_history_delete.xml',
        'wizard/import_day_plans.xml',
        'views/user_define_dev.xml',
        'views/pre_date_train_infos.xml',
        'views/week_work_class_info.xml',
        'views/import_pre_day_miles_info.xml',
        'views/mies_plan_wizard.xml'],

    'qweb': [
        "static/xml/qweb_templates.xml",
        "static/xml/search.xml",
        "static/xml/action_template.xml",
        "static/xml/year_plan_editor.xml",
        "static/xml/month_plan_editor.xml",
        "static/xml/month_plan_works.xml",
        "static/xml/week_plan_editor.xml",
        "static/xml/week_plan_summary.xml",
        "static/xml/day_plan_summary.xml",
        "static/xml/plan_preview.xml",
        "static/xml/plan_conflict_check.xml",
        "static/xml/misc.xml",
        "static/xml/bdms_template.xml",
    ],

    'application': True
}
