# -*- coding: utf-8 -*-
{
    'name': "metro_park_dispatch",
    'summary': """调度计划""",
    'description': """
        调度计划
    """,
    'author': "crax",
    'website': "http://www.funenc.com",

    'category': 'funenc',
    'version': '1.0',

    'depends': ['base',
                'metro_park_base',
                'metro_park_interlock',
                'metro_park_maintenance',
                'funenc_socket_io'],
    'data': [
        "views/assets.xml",

        'security/ir.model.access.csv',
        'security/group_data.xml',

        "views/root_menu.xml",
        "views/construction_dispatch.xml",
        "views/construction_sync_record.xml",
        "views/train_back_plan.xml",
        "views/day_run_plan.xml",
        "views/train_back_plan.xml",
        "views/train_out_plan.xml",
        "views/add_new_back_plan.xml",
        "views/add_new_out_plan.xml",
        "views/back_plan_alarm.xml",
        "views/out_plan_alarm.xml",
        "views/report_train_point.xml",
        "views/plan_import_wizard.xml",
        "views/dispatch_request.xml",
        "views/dispatch_notice.xml",
        "views/dispatch_detail.xml",
        "views/request_detail_log.xml",
        "views/dispatch_route_detail.xml",
        "views/route_command.xml",
        "views/detain_wizard.xml",
        'views/detain_his_info.xml',

        "views/cur_train_manage.xml",
        'views/cur_train_map_display.xml',
        'views/import_time_table.xml',
        'views/day_types.xml',
        'views/nor_time_table_config.xml',
        'views/special_days_config.xml',
        'views/change_time_table_wizard.xml',
        'views/real_time_table.xml',
        'views/init_wizard.xml',
        'views/set_cur_location_wizard.xml',
        'views/set_cur_location_wizard.xml',
        'views/dev_fault_report.xml',
        'views/park_dispatch_map.xml',
        "views/cur_train_map_action.xml",

        'views/report_point_history.xml',
        'views/dispatch_request_operation_log.xml',
        'views/train_in_out_log.xml',
        'views/dispatch_detail_route_info.xml',
        'views/import_run_plan_wizard.xml',
        'views/dispatch_requirement.xml',
        'views/operation.xml',
        'views/train_num.xml',
        'views/run_train/track_config.xml',
        'views/run_train/track_view.xml',
        'views/wizard/plan_export_wizard.xml',
        'views/chose_position_wizard.xml',
        'views/construction/ir_cron.xml',
        'views/construction/construction_area.xml',
        'views/construction/construction_plan.xml',
        'views/train_back_plan_log.xml',
        'views/menus.xml',
        'views/ats_position_wizard.xml',
        'views/fault_history.xml',

        'data/day_types.xml',
        'data/time_table_config.xml',
        'data/run_time_table_sequence.xml',
        'data/dispatch_notice_sequence.xml',
        'data/cur_train_manage.xml',
        'data/dispatch_requirement.xml',
        'data/operation.xml',
        'data/train_num.xml',
        'data/detain_reason.xml',

        'views/construction/ir_cron.xml',
        'views/construction/construction_area.xml',
        'views/construction/construction_plan.xml',
        'views/construction/syn_wizard.xml',
        'views/menus.xml',
        'views/work_shop_day_plan_data.xml',
        'views/work_shop_day_plan.xml',
        'views/work_shop_day_plan.xml',
        'views/run_train_wizard.xml',
        'views/day_run_plan_compute_wizard.xml',
        'views/train_miles_import.xml'
    ],

    'qweb': [
        'static/xml/*.xml'
    ],

    'application': True
}
